[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "build"
  command = "CI= npm run build"

 [[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000,
    '''